In [8]:
import pandas as pd
import numpy as np
import datetime

# Set pandas display option to prevent scientific notation
pd.options.display.float_format = '{:.3f}'.format

# Load the dataset
df = pd.read_csv('d:/Python/FinancialRisk/Data/Loan.csv')

# Convert ApplicationDate to datetime
df['ApplicationDate'] = pd.to_datetime(df['ApplicationDate'])

print("\n--- First 5 Rows ---")
print(df.head())

--- First 5 Rows ---
  ApplicationDate  Age  AnnualIncome  CreditScore EmploymentStatus  \
0      2018-01-01   45         39948          617         Employed
1      2018-01-02   38         39709          628         Employed
2      2018-01-03   47         40724          570         Employed
3      2018-01-04   58         69084          545         Employed
4      2018-01-05   37        103264          594         Employed

  EducationLevel  Experience  LoanAmount  LoanDuration MaritalStatus  ...  \
0         Master          22       13152            48       Married  ...
1      Associate          15       26045            48        Single  ...
2       Bachelor          26       17627            36       Married  ...
3    High School          34       37898            96        Single  ...
4      Associate          17        9184            36       Married  ...

   MonthlyIncome UtilityBillsPaymentHistory  JobTenure  NetWorth  \
0       3329.000                      0.725         11    126928
1       3309.083                      0.935          3     43609
2       3393.667                      0.872          6      5205
3       5757.000                      0.896          5     99452
4       8605.333                      0.941          5    227019

   BaseInterestRate  InterestRate  MonthlyLoanPayment  TotalDebtToIncomeRatio  \
0             0.200         0.228             419.806                   0.181
1             0.207         0.201             794.054                   0.390
2             0.218         0.213             666.407                   0.462
3             0.300         0.301            1047.507                   0.313
4             0.197         0.176             330.179                   0.070

  LoanApproved  RiskScore
0            0     49.000
1            0     52.000
2            0     52.000
3            0     54.000
4            1     36.000

[5 rows x 36 columns]

In [9]:
# --- Initial Data Exploration ---
print("--- Dataset Info ---")
df.info()
df.isna().sum()

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApplicationDate             20000 non-null  datetime64[ns]
 1   Age                         20000 non-null  int64
 2   AnnualIncome                20000 non-null  int64
 3   CreditScore                 20000 non-null  int64
 4   EmploymentStatus            20000 non-null  object
 5   EducationLevel              20000 non-null  object
 6   Experience                  20000 non-null  int64
 7   LoanAmount                  20000 non-null  int64
 8   LoanDuration                20000 non-null  int64
 9   MaritalStatus               20000 non-null  object
 10  NumberOfDependents          20000 non-null  int64
 11  HomeOwnershipStatus         20000 non-null  object
 12  MonthlyDebtPayments         20000 non-null  int64
 13  CreditCardUtilizationRate   20000 non-null  float64
 14  NumberOfOpenCreditLines     20000 non-null  int64
 15  NumberOfCreditInquiries     20000 non-null  int64
 16  DebtToIncomeRatio           20000 non-null  float64
 17  BankruptcyHistory           20000 non-null  int64
 18  LoanPurpose                 20000 non-null  object
 19  PreviousLoanDefaults        20000 non-null  int64
 20  PaymentHistory              20000 non-null  int64
 21  LengthOfCreditHistory       20000 non-null  int64
 22  SavingsAccountBalance       20000 non-null  int64
 23  CheckingAccountBalance      20000 non-null  int64
 24  TotalAssets                 20000 non-null  int64
 25  TotalLiabilities            20000 non-null  int64
 26  MonthlyIncome               20000 non-null  float64
 27  UtilityBillsPaymentHistory  20000 non-null  float64
 28  JobTenure                   20000 non-null  int64
 29  NetWorth                    20000 non-null  int64
 30  BaseInterestRate            20000 non-null  float64
 31  InterestRate                20000 non-null  float64
 32  MonthlyLoanPayment          20000 non-null  float64
 33  TotalDebtToIncomeRatio      20000 non-null  float64
 34  LoanApproved                20000 non-null  int64
 35  RiskScore                   20000 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(21), object(5)
memory usage: 5.5+ MB

ApplicationDate               0
Age                           0
AnnualIncome                  0
CreditScore                   0
EmploymentStatus              0
EducationLevel                0
Experience                    0
LoanAmount                    0
LoanDuration                  0
MaritalStatus                 0
NumberOfDependents            0
HomeOwnershipStatus           0
MonthlyDebtPayments           0
CreditCardUtilizationRate     0
NumberOfOpenCreditLines       0
NumberOfCreditInquiries       0
DebtToIncomeRatio             0
BankruptcyHistory             0
LoanPurpose                   0
PreviousLoanDefaults          0
PaymentHistory                0
LengthOfCreditHistory         0
SavingsAccountBalance         0
CheckingAccountBalance        0
TotalAssets                   0
TotalLiabilities              0
MonthlyIncome                 0
UtilityBillsPaymentHistory    0
JobTenure                     0
NetWorth                      0
BaseInterestRate              0
InterestRate                  0
MonthlyLoanPayment            0
TotalDebtToIncomeRatio        0
LoanApproved                  0
RiskScore                     0
dtype: int64

In [10]:
# --- Column Type Grouping ---
print("\n--- Column Type Groupings ---")
numerical_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print(f"Numerical columns ({len(numerical_cols)}): {numerical_cols}")
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(f"Categorical columns ({len(categorical_cols)}): {categorical_cols}")
datetime_cols = df.select_dtypes(include=['datetime64']).columns.tolist()
print(f"Datetime columns ({len(datetime_cols)}): {datetime_cols}")

--- Column Type Groupings ---
Numerical columns (30): ['Age', 'AnnualIncome', 'CreditScore', 'Experience', 'LoanAmount', 'LoanDuration', 'NumberOfDependents', 'MonthlyDebtPayments', 'CreditCardUtilizationRate', 'NumberOfOpenCreditLines', 'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory', 'PreviousLoanDefaults', 'PaymentHistory', 'LengthOfCreditHistory', 'SavingsAccountBalance', 'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities', 'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth', 'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment', 'TotalDebtToIncomeRatio', 'LoanApproved', 'RiskScore']
Categorical columns (5): ['EmploymentStatus', 'EducationLevel', 'MaritalStatus', 'HomeOwnershipStatus', 'LoanPurpose']
Datetime columns (1): ['ApplicationDate']

In [11]:
# --- Missing Data Check ---
print("\n--- Missing Values Summary ---")
missing_data = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_df = pd.DataFrame({'Missing Values': missing_data, 'Percentage': missing_percent})
print(missing_df[missing_df['Missing Values'] > 0])
if missing_df['Missing Values'].sum() == 0:
    print("No missing values found in the dataset.")

# --- Descriptive Statistics ---
print("\n--- Descriptive Statistics for Numerical Columns ---")
print(df[numerical_cols].describe())

print("\n--- Value Counts for Categorical Columns ---")
for col in categorical_cols:
    print(f"\n--- {col} (Unique Values: {df[col].nunique()}) ---")
    print(df[col].value_counts())

--- Missing Values Summary ---
Empty DataFrame
Columns: [Missing Values, Percentage]
Index: []
No missing values found in the dataset.

--- Descriptive Statistics for Numerical Columns ---
            Age  AnnualIncome  CreditScore  Experience  LoanAmount  \
count 20000.000     20000.000    20000.000   20000.000   20000.000
mean     39.753     59161.474      571.612      17.523   24882.868
std      11.623     40350.845       50.997      11.317   13427.421
min      18.000     15000.000      343.000       0.000    3674.000
25%      32.000     31679.000      540.000       9.000   15575.000
50%      40.000     48566.000      578.000      17.000   21914.500
75%      48.000     74391.000      609.000      25.000   30835.000
max      80.000    485341.000      712.000      61.000  184732.000

       LoanDuration  NumberOfDependents  MonthlyDebtPayments  \
count     20000.000           20000.000            20000.000
mean         54.057               1.517              454.293
std          24.665               1.386              240.508
min          12.000               0.000               50.000
25%          36.000               0.000              286.000
50%          48.000               1.000              402.000
75%          72.000               2.000              564.000
max         120.000               5.000             2919.000

       CreditCardUtilizationRate  NumberOfOpenCreditLines  ...  MonthlyIncome  \
count                  20000.000                20000.000  ...      20000.000
mean                       0.286                    3.023  ...       4891.716
std                        0.160                    1.736  ...       3296.772
min                        0.001                    0.000  ...       1250.000
25%                        0.161                    2.000  ...       2629.583
50%                        0.267                    3.000  ...       4034.750
75%                        0.391                    4.000  ...       6163.000
max                        0.917                   13.000  ...      25000.000

       UtilityBillsPaymentHistory  JobTenure    NetWorth  BaseInterestRate  \
count                   20000.000  20000.000   20000.000         20000.000
mean                        0.800      5.003   72294.319             0.239
std                         0.121      2.237  117920.021             0.036
min                         0.259      0.000    1000.000             0.130
25%                         0.727      3.000    8734.750             0.214
50%                         0.821      5.000   32855.500             0.236
75%                         0.892      6.000   88825.500             0.262
max                         0.999     16.000 2603208.000             0.405

       InterestRate  MonthlyLoanPayment  TotalDebtToIncomeRatio  LoanApproved  \
count     20000.000           20000.000               20000.000     20000.000
mean          0.239             911.607                   0.402         0.239
std           0.042             674.583                   0.339         0.426
min           0.113              97.030                   0.016         0.000
25%           0.209             493.764                   0.180         0.000
50%           0.235             728.511                   0.303         0.000
75%           0.266            1112.771                   0.509         0.000
max           0.447           10892.630                   4.648         1.000

       RiskScore
count  20000.000
mean      50.767
std        7.778
min       28.800
25%       46.000
50%       52.000
75%       56.000
max       84.000

[8 rows x 30 columns]

--- Value Counts for Categorical Columns ---

--- EmploymentStatus (Unique Values: 3) ---
EmploymentStatus
Employed         17036
Self-Employed     1573
Unemployed        1391
Name: count, dtype: int64

--- EducationLevel (Unique Values: 5) ---
EducationLevel
Bachelor       6054
High School    5908
Associate      4034
Master         3050
Doctorate       954
Name: count, dtype: int64

--- MaritalStatus (Unique Values: 4) ---
MaritalStatus
Married     10041
Single       6078
Divorced     2882
Widowed       999
Name: count, dtype: int64

--- HomeOwnershipStatus (Unique Values: 4) ---
HomeOwnershipStatus
Mortgage    7939
Rent        6087
Own         3938
Other       2036
Name: count, dtype: int64

--- LoanPurpose (Unique Values: 5) ---
LoanPurpose
Home                  5925
Debt Consolidation    5027
Auto                  4034
Education             3008
Other                 2006
Name: count, dtype: int64

In [12]:
# --- Target Variable Analysis ---
print("\n--- LoanApproved Distribution ---")
print(df['LoanApproved'].value_counts())
print("\n--- LoanApproved Distribution (%) ---")
print(df['LoanApproved'].value_counts(normalize=True) * 100)

# --- Data Quality Checks ---
print("\n--- Data Quality Checks ---")
print(f"Number of duplicate rows: {df.duplicated().sum()}")

print("\n--- Datatype Breakdown ---")
print(df.dtypes.value_counts())

print("\n--- Range Checks for Key Variables ---")
key_vars = ['Age', 'AnnualIncome', 'CreditScore', 'LoanAmount']
for var in key_vars:
    print(f"{var}: Min={df[var].min()}, Max={df[var].max()}")

# --- Grouped Statistics ---
print("\n--- Grouped Statistics (Approved vs. Rejected) ---")
# Exclude boolean 'LoanApproved' from numerical columns for this aggregation
numerical_cols_for_grouping = [col for col in numerical_cols if col != 'LoanApproved']
print(df.groupby('LoanApproved')[numerical_cols_for_grouping].agg(['mean', 'median', 'std']))

# --- Crosstabulation Analysis ---
print("\n--- Approval Rate by Employment Status (% of Total for each status) ---")
print(pd.crosstab(df['EmploymentStatus'], df['LoanApproved'], normalize='index') * 100)

print("\n\nInitial analysis complete.")

--- LoanApproved Distribution ---
LoanApproved
0    15220
1     4780
Name: count, dtype: int64

--- LoanApproved Distribution (%) ---
LoanApproved
0   76.100
1   23.900
Name: proportion, dtype: float64

--- Data Quality Checks ---
Number of duplicate rows: 0

--- Datatype Breakdown ---
int64             21
float64            9
object             5
datetime64[ns]     1
Name: count, dtype: int64

--- Range Checks for Key Variables ---
Age: Min=18, Max=80
AnnualIncome: Min=15000, Max=485341
CreditScore: Min=343, Max=712
LoanAmount: Min=3674, Max=184732

--- Grouped Statistics (Approved vs. Rejected) ---
                Age               AnnualIncome                      \
               mean median    std         mean    median       std
LoanApproved
0            38.834 39.000 11.680    45641.461 40557.500 24079.007
1            42.677 42.000 10.936   102210.551 91269.500 50313.413

             CreditScore                Experience  ... InterestRate  \
                    mean  median    std       mean  ...          std
LoanApproved                                        ...
0                567.554 574.000 50.918     16.630  ...        0.042
1                584.534 591.000 49.066     20.365  ...        0.035

             MonthlyLoanPayment                 TotalDebtToIncomeRatio         \
                           mean  median     std                   mean median
LoanApproved
0                       981.268 791.221 718.462                  0.480  0.381
1                       689.799 576.035 442.537                  0.154  0.138

                   RiskScore
               std      mean median   std
LoanApproved
0            0.351    54.106 54.000 5.302
1            0.083    40.133 40.000 3.880

[2 rows x 87 columns]

--- Approval Rate by Employment Status (% of Total for each status) ---
LoanApproved          0      1
EmploymentStatus
Employed         75.998 24.002
Self-Employed    72.155 27.845
Unemployed       81.812 18.188


Initial analysis complete.